# Define the version of the docker-compose file format
version: '3.8'

services:
  # Database service configuration using Microsoft SQL Server 2022
  db:
    # Use the official SQL Server image from Microsoft Container Registry
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      # Set the SA (system administrator) password for SQL Server
      SA_PASSWORD: "Riwi2025**"
      # Automatically accept the End User License Agreement (EULA)
      ACCEPT_EULA: "Y"
    ports:
      # Map port 1433 of the container (default SQL Server port) to port 1433 on the host
      - "1433:1433"
    volumes:
      # Persist SQL Server data by mounting a named volume
      - sql-data:/var/opt/mssql
    networks:
      # Connect this service to the "member-network" network
      - member-network

  # Member service configuration
  memberservice:
    # Build the memberservice image from the specified context and Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Use environment variables defined in the .env.production file
    env_file:
      - .env.production
    ports:
      # Map port 8080 of the container to port 8080 on the host
      - "8080:8080"
    # Ensure the memberservice starts only after the db service is up
    depends_on:
      - db
    networks:
      # Connect this service to the "member-network" network
      - member-network

# Define custom networks for service communication
networks:
  member-network:
    driver: bridge

# Define named volumes for persistent data storage
volumes:
  sql-data:
